<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Interfaces\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <None Remove="Interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StayEasy.BE\StayEasy.BE.csproj" />
    <ProjectReference Include="..\StayEasy.DAL\StayEasy.DAL.csproj" />
    <ProjectReference Include="..\StayEasy.Seguridad\StayEasy.Seguridad.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
