<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Gestores\**" />
    <EmbeddedResource Remove="Gestores\**" />
    <None Remove="Gestores\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StayEasy.BE\StayEasy.BE.csproj" />
    <ProjectReference Include="..\StayEasy.MPP\StayEasy.MPP.csproj" />
    <ProjectReference Include="..\StayEasy.Seguridad\StayEasy.Seguridad.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
